### ISSUE TITLE
Are you a human?" prompt

### ISSUE THREAD

**Issue by maxxam95** [Zeeshanahmad4/Automating-ChatGPT-with-Python-and-Selenium#1]
Hey, I am struggling with the "Are you a human?" prompt which pops up. Do you have a way of dealing with that?

**Comment by AI-Enthusiast** [comment]
having the same problem. I put it into a loop and sleep to wait while I click through the "are you human" prompt, but that doesn't seem to do it either

**Comment by Zeeshanahmad4** [comment]
Hey sorry for the delay response if you have Chatgpt plus it should not apears. 
its cloud service using for protection for free account using bots.
